### PR TITLE
Added ShortPreference Class

### PR DESCRIPTION
**Pull request by matthew-compton**
Fixes Issue #5

### CODE REVIEW

**Comment by johnjohndoe** [comment]
Thanks for the work. Can you please add tests for the class. Please squash the commits and force push them onto the branch.

**Comment by matthew-compton** [comment]
How's it look now?

**Comment by johnjohndoe** [comment]
I took some time to review your pull request. I like to encourage you to rewrite the implementation. Since you store the `short` values in an `Integer` preference you can reuse the `IntegerPreference` class. Please have a look at the [TypedPreferences-Commons](https://github.com/johnjohndoe/TypedPreferences/wiki/TypedPreferences-Commons) where I reused existing classes, too.

Please squash and rebase your branch onto the current master after you are done.

**Comment by matthew-compton** [comment]
That was a good idea, and I think it's better now. Let me know what you think!

**Comment by johnjohndoe** [comment]
Please rebase your branch onto master. I updated the project setup.

**Comment by matthew-compton** [comment]
Good? :+1:

**Comment by johnjohndoe** [comment]
@matthew-compton Sorry, that it took so long to review this. I would be happy to integrate your work after you updated the files. Feel free to squash the changes and force push this branch.

**Comment by matthew-compton** [comment]
I think it's ready!

**Comment by matthew-compton** [comment]
Fixed up!

**Comment by johnjohndoe** [comment]
Thank you for your work and patience!

**Comment by johnjohndoe** [comment]
Finally this has been released in [v.2.1.0](https://github.com/johnjohndoe/TypedPreferences/releases/tag/v.2.1.0). Thank you once again .-)

**Pull request merged**
