### PR TITLE
Added StringSetPreference Class

### PR DESCRIPTION
**Pull request by matthew-compton**
Fixes Issue #6

### CODE REVIEW

**Comment by johnjohndoe** [comment]
Thanks for the work. Can you please add tests for the class. Please squash the commits and force push them onto the branch.

**Comment by matthew-compton** [comment]
How's it look now?

**Comment by johnjohndoe** [comment]
Looks nice :) I will review your work in the next days.

**Comment by johnjohndoe** [comment]
I did not notice `@TargetApi(Build.VERSION_CODES.HONEYCOMB)` at the first look.
I did increase the minSdkVersion before. I would like to delay this feature to be part of a new major version. Before that I would probably first add all primitive types such as `short` to the library which do not require an update of the minSdkVersion.

**Comment by matthew-compton** [comment]
Sounds good. Thanks for the feedback!

**Comment by johnjohndoe** [comment]
Can you please rebase onto master once again? Thank you.

**Comment by matthew-compton** [comment]
Is this what you wanted?

**Comment by johnjohndoe** [comment]
No. I wanted you to rebase your commit `beb330dda05050c90b9e12df13f49574dab0ac19` onto current `master` which is `9608591950f6e812600d7d8f247d23aa818234b4`.

Try the following:

1. Synchronize your `master` branch with mine:

    ``` bash
    $ git checkout master
    $ git pull johnjohndoe master
    $ git push origin master
    ```

2. Rebase your commit:

    ``` bash
    $ git checkout beb330dda05050c90b9e12df13f49574dab0ac19
    $ git checkout -b feature/support-string-set
    $ git rebase master feature/support-string-set
    $ git push origin feature/support-string-set -f
    ```

**Comment by matthew-compton** [comment]
I gave up on this. I created a new PR.

**Comment by johnjohndoe** [comment]
You can update a former branch (and pull request) if you force push your branch via `git push -f origin branch-name`.

**Pull request closed without merging**
