### PR TITLE
Added support for Sets of Strings

### PR DESCRIPTION
**Pull request by matthew-compton**
Fixes Issue #6

### CODE REVIEW

**Comment by matthew-compton** [comment]
This should be what you want. If it's not, let me know.

**Comment by johnjohndoe** [comment]
You did not update your master branch. Here is what you should do:

1. Synchronize your `master` branch with mine:

    ``` bash
    $ git remote add johnjohndoe git@github.com:johnjohndoe/TypedPreferences.git
    $ git checkout master
    $ git pull johnjohndoe master
    $ git push origin master
    ```

2. Rebase your commit:

    ``` bash
    $ git rebase master mc/support-string-set
    $ git push origin mc/support-string-set -f
    ```

**Comment by matthew-compton** [comment]
I did all of that. Everything is up to date. Those commands had no changing effects on this branch.

**Comment by matthew-compton** [comment]
I can't reopen the other PR because of this one.

**Comment by matthew-compton** [comment]
I have no idea what you want me to do or even why. From what I can tell, this branch does exactly what the title suggests, passes all tests, and seems up to standard with your conventions. I'm just not sure what you want from me here.

**Comment by johnjohndoe** [comment]
Understood. You need to pull my master first and push it to your remote as described in step 1.

**Comment by matthew-compton** [comment]
I don't have permission for:
`git pull johnjohndoe master`

**Comment by matthew-compton** [comment]
Ugh. I did it again. Sorry, this is all a lot to learn immediately.

**Comment by ming13** [comment]
:+1: 

Any news on releasing this?

**Comment by johnjohndoe** [comment]
@ming13 I am actually not quite sure if the library should include any of the complex types. I started the library to only contain primitives. I feel like when I add complex types it quickly becomes too heavy and fails its purpose. I already discussed this with @matthew-compton. Also, adding `Set<String>` would require to increase the minimum SDK level from 9 to 11.
What's your opinion on this?

**Comment by ming13** [comment]
@johnjohndoe As I see it the purpose of the library is to mirror `SharedPreferences` API in a more efficient way, not add a superset API on top of it. From that perspective the `Set` support is reasonable. If I am wrong—this doesn’t apply. Purely your choice ;-)

**Comment by johnjohndoe** [comment]
One idea I came up with is to move these changes into a major version upgrade with regards to [semantic versioning](http://semver.org/). At the same time I would probably change the package name from `info.metadude.android:typed-preferences:{$version}` to `info.metadude.android:typed-preferences3:{$version}` as being done at [OkHttp](https://github.com/square/okhttp) and [Retrofit](https://github.com/square/retrofit) nowadays. This would allow to still release 2.x versions later on if needed. - What do you think about this?

**Comment by ming13** [comment]
@johnjohndoe From my point of view it is not necessary to use a major version for this and change package name. It is not a major change and it doesn’t break or change anything. It is just an addition to existing API.

**Comment by johnjohndoe** [comment]
@ming13 You forget about the `minSdkVersion` increase and thereby excluding former users of the library.

**Comment by ming13** [comment]
@johnjohndoe In this case yep, it does make sense. Not sure about the package name though. The reason behind OkHttp decision was to make the migration process more easy. In our case there is no migration as it is, only the decision about `minSdkVersion`.

**Comment by johnjohndoe** [comment]
@ming13 I consider this because I might wanna add further primitive types such as `Byte` later on would then only be available in 3.x versions.

**Comment by ming13** [comment]
@johnjohndoe Still, not breaking anything :-)

**Comment by tasomaniac** [comment]
What's wrong about making minSdkLevel 11? No one would argue.

**Comment by johnjohndoe** [comment]
@tasomaniac I run a project my own which still supports minSdkVersion 8.

**Comment by tasomaniac** [comment]
I see :) I respect you then.

**Comment by johnjohndoe** [comment]
Hey @matthew-compton. Sorry for this ever-lasting pull request. I finally want to make a decision here too not support `Sets` in this library. I also believe that people are switching to Kotlin nowadays which will let this library become redundant. Please be assured I nevertheless highly appreciate your contribution to open source!

**Pull request closed without merging**
